#!/usr/bin/env python3
"""Builds tools/storefront/mu-plugins/f360-promesa-avisame-staging4.php from the storefront snippets (single source).
PDP: f360-promesa-avisame.html · checkout + Pedido recibido: f360-promesa-checkout.html (+ the line ids, no personal data)."""
import pathlib
root = pathlib.Path(__file__).resolve().parents[2] / 'tools' / 'storefront'
pdp = (root / 'f360-promesa-avisame.html').read_text()
chk = (root / 'f360-promesa-checkout.html').read_text()
php = '''<?php
/**
 * Fuxia 360 · CRO-5 + CRO-6 (Mario 2026-10-05) — STAGING4 ONLY. GENERATED by scripts/f360/build_storefront_muplugin.py; do not edit.
 * PDP: ONE delivery promise from Fuxia 360 + verifiable trust + "Avísame cuando llegue" (f360-promesa-avisame.html).
 * Checkout + "Pedido recibido": the SAME promise per line + "Talla MX" presentation (f360-promesa-checkout.html).
 * Install: copy to wp-content/mu-plugins/ on staging4. Rollback: delete the file and purge the cache.
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }
if ( false === strpos( (string) wp_parse_url( home_url(), PHP_URL_HOST ), 'staging4.' ) ) { return; }   // never on production

add_action( 'wp_footer', function () {
	if ( ! function_exists( 'is_product' ) || ! is_product() ) { return; }
	?>
''' + pdp + '''
	<?php
}, 120 );

// Checkout and "Pedido recibido": Woo variation ids of the lines, in the order WooCommerce paints them (no personal data).
function f360_promesa_lines() {
	$lines = array();
	if ( function_exists( 'is_order_received_page' ) && is_order_received_page() ) {
		$order_id = absint( get_query_var( 'order-received' ) );
		$order    = $order_id ? wc_get_order( $order_id ) : null;
		$key      = isset( $_GET['key'] ) ? wc_clean( wp_unslash( $_GET['key'] ) ) : '';
		if ( ! $order || ! hash_equals( (string) $order->get_order_key(), (string) $key ) ) { return array(); }
		foreach ( $order->get_items() as $item ) {
			$v = (int) $item->get_variation_id();
			$lines[] = array( 'v' => $v ? $v : (int) $item->get_product_id() );
		}
	} elseif ( function_exists( 'is_checkout' ) && is_checkout() && WC()->cart ) {
		foreach ( WC()->cart->get_cart() as $ci ) {
			$v = (int) ( $ci['variation_id'] ?? 0 );
			$lines[] = array( 'v' => $v ? $v : (int) ( $ci['product_id'] ?? 0 ) );
		}
	}
	return $lines;
}
add_action( 'wp_footer', function () {
	if ( ! function_exists( 'is_checkout' ) || ! is_checkout() ) { return; }
	$lines = f360_promesa_lines();
	if ( ! $lines ) { return; }
	echo '<script>window.F360_LINES = ' . wp_json_encode( $lines ) . ';</script>';
	?>
''' + chk + '''
	<?php
}, 121 );
'''
(root / 'mu-plugins' / 'f360-promesa-avisame-staging4.php').write_text(php)
print('ok', len(php))
